// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BrokerClient is the client API for Broker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerClient interface {
	GetProviders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Providers, error)
	Register(ctx context.Context, opts ...grpc.CallOption) (Broker_RegisterClient, error)
}

type brokerClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerClient(cc grpc.ClientConnInterface) BrokerClient {
	return &brokerClient{cc}
}

func (c *brokerClient) GetProviders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Providers, error) {
	out := new(Providers)
	err := c.cc.Invoke(ctx, "/service.Broker/GetProviders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) Register(ctx context.Context, opts ...grpc.CallOption) (Broker_RegisterClient, error) {
	stream, err := c.cc.NewStream(ctx, &Broker_ServiceDesc.Streams[0], "/service.Broker/Register", opts...)
	if err != nil {
		return nil, err
	}
	x := &brokerRegisterClient{stream}
	return x, nil
}

type Broker_RegisterClient interface {
	Send(*Ping) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type brokerRegisterClient struct {
	grpc.ClientStream
}

func (x *brokerRegisterClient) Send(m *Ping) error {
	return x.ClientStream.SendMsg(m)
}

func (x *brokerRegisterClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BrokerServer is the server API for Broker service.
// All implementations must embed UnimplementedBrokerServer
// for forward compatibility
type BrokerServer interface {
	GetProviders(context.Context, *Empty) (*Providers, error)
	Register(Broker_RegisterServer) error
	mustEmbedUnimplementedBrokerServer()
}

// UnimplementedBrokerServer must be embedded to have forward compatible implementations.
type UnimplementedBrokerServer struct {
}

func (UnimplementedBrokerServer) GetProviders(context.Context, *Empty) (*Providers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProviders not implemented")
}
func (UnimplementedBrokerServer) Register(Broker_RegisterServer) error {
	return status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedBrokerServer) mustEmbedUnimplementedBrokerServer() {}

// UnsafeBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerServer will
// result in compilation errors.
type UnsafeBrokerServer interface {
	mustEmbedUnimplementedBrokerServer()
}

func RegisterBrokerServer(s grpc.ServiceRegistrar, srv BrokerServer) {
	s.RegisterService(&Broker_ServiceDesc, srv)
}

func _Broker_GetProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GetProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Broker/GetProviders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GetProviders(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BrokerServer).Register(&brokerRegisterServer{stream})
}

type Broker_RegisterServer interface {
	SendAndClose(*Empty) error
	Recv() (*Ping, error)
	grpc.ServerStream
}

type brokerRegisterServer struct {
	grpc.ServerStream
}

func (x *brokerRegisterServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *brokerRegisterServer) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Broker_ServiceDesc is the grpc.ServiceDesc for Broker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Broker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.Broker",
	HandlerType: (*BrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProviders",
			Handler:    _Broker_GetProviders_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _Broker_Register_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "broker.proto",
}

// ProviderClient is the client API for Provider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProviderClient interface {
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProviderInfo, error)
	Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Utilization, error)
	Init(ctx context.Context, in *Simulation, opts ...grpc.CallOption) (*Empty, error)
	CompileSync(ctx context.Context, in *SimulationId, opts ...grpc.CallOption) (*Binary, error)
	CompileAsync(ctx context.Context, in *SimulationId, opts ...grpc.CallOption) (*Accepted, error)
	RunSync(ctx context.Context, in *SimulationRun, opts ...grpc.CallOption) (*StorageRef, error)
	RunAsync(ctx context.Context, in *SimulationRun, opts ...grpc.CallOption) (*Accepted, error)
}

type providerClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderClient(cc grpc.ClientConnInterface) ProviderClient {
	return &providerClient{cc}
}

func (c *providerClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProviderInfo, error) {
	out := new(ProviderInfo)
	err := c.cc.Invoke(ctx, "/service.Provider/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Utilization, error) {
	out := new(Utilization)
	err := c.cc.Invoke(ctx, "/service.Provider/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) Init(ctx context.Context, in *Simulation, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/service.Provider/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) CompileSync(ctx context.Context, in *SimulationId, opts ...grpc.CallOption) (*Binary, error) {
	out := new(Binary)
	err := c.cc.Invoke(ctx, "/service.Provider/CompileSync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) CompileAsync(ctx context.Context, in *SimulationId, opts ...grpc.CallOption) (*Accepted, error) {
	out := new(Accepted)
	err := c.cc.Invoke(ctx, "/service.Provider/CompileAsync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) RunSync(ctx context.Context, in *SimulationRun, opts ...grpc.CallOption) (*StorageRef, error) {
	out := new(StorageRef)
	err := c.cc.Invoke(ctx, "/service.Provider/RunSync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) RunAsync(ctx context.Context, in *SimulationRun, opts ...grpc.CallOption) (*Accepted, error) {
	out := new(Accepted)
	err := c.cc.Invoke(ctx, "/service.Provider/RunAsync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderServer is the server API for Provider service.
// All implementations must embed UnimplementedProviderServer
// for forward compatibility
type ProviderServer interface {
	Info(context.Context, *Empty) (*ProviderInfo, error)
	Status(context.Context, *Empty) (*Utilization, error)
	Init(context.Context, *Simulation) (*Empty, error)
	CompileSync(context.Context, *SimulationId) (*Binary, error)
	CompileAsync(context.Context, *SimulationId) (*Accepted, error)
	RunSync(context.Context, *SimulationRun) (*StorageRef, error)
	RunAsync(context.Context, *SimulationRun) (*Accepted, error)
	mustEmbedUnimplementedProviderServer()
}

// UnimplementedProviderServer must be embedded to have forward compatible implementations.
type UnimplementedProviderServer struct {
}

func (UnimplementedProviderServer) Info(context.Context, *Empty) (*ProviderInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedProviderServer) Status(context.Context, *Empty) (*Utilization, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedProviderServer) Init(context.Context, *Simulation) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedProviderServer) CompileSync(context.Context, *SimulationId) (*Binary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompileSync not implemented")
}
func (UnimplementedProviderServer) CompileAsync(context.Context, *SimulationId) (*Accepted, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompileAsync not implemented")
}
func (UnimplementedProviderServer) RunSync(context.Context, *SimulationRun) (*StorageRef, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunSync not implemented")
}
func (UnimplementedProviderServer) RunAsync(context.Context, *SimulationRun) (*Accepted, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunAsync not implemented")
}
func (UnimplementedProviderServer) mustEmbedUnimplementedProviderServer() {}

// UnsafeProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProviderServer will
// result in compilation errors.
type UnsafeProviderServer interface {
	mustEmbedUnimplementedProviderServer()
}

func RegisterProviderServer(s grpc.ServiceRegistrar, srv ProviderServer) {
	s.RegisterService(&Provider_ServiceDesc, srv)
}

func _Provider_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Provider/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Provider/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Status(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Simulation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Provider/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Init(ctx, req.(*Simulation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_CompileSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulationId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).CompileSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Provider/CompileSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).CompileSync(ctx, req.(*SimulationId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_CompileAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulationId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).CompileAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Provider/CompileAsync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).CompileAsync(ctx, req.(*SimulationId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_RunSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulationRun)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).RunSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Provider/RunSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).RunSync(ctx, req.(*SimulationRun))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_RunAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulationRun)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).RunAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Provider/RunAsync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).RunAsync(ctx, req.(*SimulationRun))
	}
	return interceptor(ctx, in, info, handler)
}

// Provider_ServiceDesc is the grpc.ServiceDesc for Provider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Provider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.Provider",
	HandlerType: (*ProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Provider_Info_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Provider_Status_Handler,
		},
		{
			MethodName: "Init",
			Handler:    _Provider_Init_Handler,
		},
		{
			MethodName: "CompileSync",
			Handler:    _Provider_CompileSync_Handler,
		},
		{
			MethodName: "CompileAsync",
			Handler:    _Provider_CompileAsync_Handler,
		},
		{
			MethodName: "RunSync",
			Handler:    _Provider_RunSync_Handler,
		},
		{
			MethodName: "RunAsync",
			Handler:    _Provider_RunAsync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "broker.proto",
}
