// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: dial_addr.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DialAddr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip   []byte `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Zone string `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"` // IPv6 scoped addressing zone
}

func (x *DialAddr) Reset() {
	*x = DialAddr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dial_addr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialAddr) ProtoMessage() {}

func (x *DialAddr) ProtoReflect() protoreflect.Message {
	mi := &file_dial_addr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialAddr.ProtoReflect.Descriptor instead.
func (*DialAddr) Descriptor() ([]byte, []int) {
	return file_dial_addr_proto_rawDescGZIP(), []int{0}
}

func (x *DialAddr) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *DialAddr) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DialAddr) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

var File_dial_addr_proto protoreflect.FileDescriptor

var file_dial_addr_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x64, 0x69, 0x61, 0x6c, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x42, 0x0a, 0x08, 0x44, 0x69,
	0x61, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x7a, 0x6f,
	0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x7a, 0x6f, 0x6e, 0x65, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_dial_addr_proto_rawDescOnce sync.Once
	file_dial_addr_proto_rawDescData = file_dial_addr_proto_rawDesc
)

func file_dial_addr_proto_rawDescGZIP() []byte {
	file_dial_addr_proto_rawDescOnce.Do(func() {
		file_dial_addr_proto_rawDescData = protoimpl.X.CompressGZIP(file_dial_addr_proto_rawDescData)
	})
	return file_dial_addr_proto_rawDescData
}

var file_dial_addr_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dial_addr_proto_goTypes = []interface{}{
	(*DialAddr)(nil), // 0: service.DialAddr
}
var file_dial_addr_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dial_addr_proto_init() }
func file_dial_addr_proto_init() {
	if File_dial_addr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dial_addr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialAddr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dial_addr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dial_addr_proto_goTypes,
		DependencyIndexes: file_dial_addr_proto_depIdxs,
		MessageInfos:      file_dial_addr_proto_msgTypes,
	}.Build()
	File_dial_addr_proto = out.File
	file_dial_addr_proto_rawDesc = nil
	file_dial_addr_proto_goTypes = nil
	file_dial_addr_proto_depIdxs = nil
}
