// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: opp_config.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OppConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// buildscript path from simulation root (optional)
	BuildScript string `protobuf:"bytes,1,opt,name=buildScript,proto3" json:"buildScript,omitempty"`
	// This is the directory in which the simulation will be executed
	BasePath string `protobuf:"bytes,2,opt,name=basePath,proto3" json:"basePath,omitempty"`
	// Simulation ini files (from simulation root)
	IniFiles []string `protobuf:"bytes,3,rep,name=iniFiles,proto3" json:"iniFiles,omitempty"`
	// Ned include directories (from simulation root)
	NedPaths []string `protobuf:"bytes,4,rep,name=nedPaths,proto3" json:"nedPaths,omitempty"`
	// Use 'opp_run -l ...' instead of running the simulation directly
	UseLib bool `protobuf:"varint,5,opt,name=useLib,proto3" json:"useLib,omitempty"`
	// TODO: Rename to executablePath
	// Simulation exe or lib (from simulation root)
	Simulation string `protobuf:"bytes,6,opt,name=simulation,proto3" json:"simulation,omitempty"`
	// TODO: Rename to makefilePath
	// Directory that (should) contain the Makefile
	SourcePath string `protobuf:"bytes,7,opt,name=sourcePath,proto3" json:"sourcePath,omitempty"`
}

func (x *OppConfig) Reset() {
	*x = OppConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opp_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OppConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OppConfig) ProtoMessage() {}

func (x *OppConfig) ProtoReflect() protoreflect.Message {
	mi := &file_opp_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OppConfig.ProtoReflect.Descriptor instead.
func (*OppConfig) Descriptor() ([]byte, []int) {
	return file_opp_config_proto_rawDescGZIP(), []int{0}
}

func (x *OppConfig) GetBuildScript() string {
	if x != nil {
		return x.BuildScript
	}
	return ""
}

func (x *OppConfig) GetBasePath() string {
	if x != nil {
		return x.BasePath
	}
	return ""
}

func (x *OppConfig) GetIniFiles() []string {
	if x != nil {
		return x.IniFiles
	}
	return nil
}

func (x *OppConfig) GetNedPaths() []string {
	if x != nil {
		return x.NedPaths
	}
	return nil
}

func (x *OppConfig) GetUseLib() bool {
	if x != nil {
		return x.UseLib
	}
	return false
}

func (x *OppConfig) GetSimulation() string {
	if x != nil {
		return x.Simulation
	}
	return ""
}

func (x *OppConfig) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

var File_opp_config_proto protoreflect.FileDescriptor

var file_opp_config_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6f, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0xd9, 0x01, 0x0a, 0x09,
	0x4f, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x75, 0x69,
	0x6c, 0x64, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x62, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x62,
	0x61, 0x73, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62,
	0x61, 0x73, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x69, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x69, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x65, 0x64, 0x50, 0x61, 0x74, 0x68, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x65, 0x64, 0x50, 0x61, 0x74, 0x68, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x4c, 0x69, 0x62, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x4c, 0x69, 0x62, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x69, 0x6d, 0x75, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x69, 0x6d,
	0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_opp_config_proto_rawDescOnce sync.Once
	file_opp_config_proto_rawDescData = file_opp_config_proto_rawDesc
)

func file_opp_config_proto_rawDescGZIP() []byte {
	file_opp_config_proto_rawDescOnce.Do(func() {
		file_opp_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_opp_config_proto_rawDescData)
	})
	return file_opp_config_proto_rawDescData
}

var file_opp_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_opp_config_proto_goTypes = []interface{}{
	(*OppConfig)(nil), // 0: service.OppConfig
}
var file_opp_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_opp_config_proto_init() }
func file_opp_config_proto_init() {
	if File_opp_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_opp_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OppConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_opp_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_opp_config_proto_goTypes,
		DependencyIndexes: file_opp_config_proto_depIdxs,
		MessageInfos:      file_opp_config_proto_msgTypes,
	}.Build()
	File_opp_config_proto = out.File
	file_opp_config_proto_rawDesc = nil
	file_opp_config_proto_goTypes = nil
	file_opp_config_proto_depIdxs = nil
}
